name: 💬 Question
description: Ask a question about the vue-modal.
title: '[Question]: '
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please make sure that you have read through our [documentation](https://github.com/kolirt/vue-modal?tab=readme-ov-file#simple-vue3-modal-package) and existing [issues](https://github.com/kolirt/vue-modal/issues).
  - type: input
    id: version
    attributes:
      label: Package version
      description: |
        Leave blank if you have not yet configured the package and have not used it.
      placeholder: v1.0.1
  - type: textarea
    id: configuration
    attributes:
      label: Package configuration
      description: |
        Show how you configured the package. You can check how to configure the package [here](https://github.com/kolirt/vue-modal?tab=readme-ov-file#setup).
        Leave blank if you have not yet configured the package and have not used it.
      placeholder: |
        createModal({
          transitionTime: 200,
          animationType: 'slideDown',
          modalStyle: {
            padding: '5rem 2rem',
            align: 'center',
            'z-index': 201
          },
          overlayStyle: {
            'background-color': 'rgba(0, 0, 0, .5)',
            'backdrop-filter': 'blur(5px)',
            'z-index': 200
          }
        })
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true