export { closeAllModals, closeModal, confirmModal, openModal } from './actions'
export { default as ModalTarget } from './components/ModalTarget.vue'
export { default as SimpleModal } from './components/layouts/SimpleModal.vue'
export { useLock } from './composables/useLock'
export { isOpened, modals } from './data'
export { $off, $on } from './event'
export { createModal } from './plugin'
export { Events, type ModalItem } from './types'
