blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/kolirt/vue-modal?tab=readme-ov-file#simple-vue3-modal-package
    about: Check the documentation for guides and examples.
